---
config:
  chat_api:
  domain_api:
  image_api:
  image_web:
  path_client: /nfs/client
  path_environment: /nfs/environment
  port_api: 18081
  post_mail:
  regis_admin:
  regis_merch:
  token_regis:
  x_api_key:
  x_token:
cloudflare:
  account_id:
  base_url: https://api.cloudflare.com/client/v4
  email:
  key:
  tunnel_id:
jenkins:
  api_key:
  api_url:
  base_url:
  domain_credentials:
  prefix_credentials:
  username:
portainer:
  api_key:
  base_url:
  endpointId:
  fromAppTemplate: true
  method: string
  swarm_id:
  type: swarm
  username:
